var GAME_LEVELS = [
  ["                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                                                              ",
   "                                                 yyyy                                         ",
   "                                          o                  o                                ",
   "                                     #                                                        ",
   "                                    xxxxxx  xxx        yyyyyx o xyy  |                        ",
   "            o                        o o x!!x     q         x!!!x                     xxx     ",
   "          o       #          q           x!!x               xxxxx                       x     ",
   "           o            yyyyyyy          xxxx                                           x     ",
   "  xx      o          <                      o o                                      r  x     ",
   "  x              xxxx      o                     # o                        q           x     ",
   "  x      x!!x    x  x                           xxxxxx                          xxxxxxxxx     ",
   "  x      xxxx    x  x      o           =                                        x             ",
   "  x   @          x  x         #              #                   o     xxxxxxxxxx             ",
   "  xxxxxxxxxxxxxxxx  xxxxxxxxxxx   xxxxxxxxxxxx         xxxxxxxx!!!xxxxxx                      ",
   "  xxxxxxxxxxxxxxxx  xxxxxxxxxxx!!!xxxxxxxxxxxx         xxxxxxxxxxxxxxxxx                      ",
   "                              x!!!x          x!!!!!!!!!x                                      ",
   "                              x!!!x          x!!!!!!!!!x                                      ",
   "                              xxxxx          xxxxxxxxxxx                                      ",
   "                                                                                              ",
   "                                                                                              "],
  ["                                      x!!x                                        -                          x!x  ",
   "                -                     x!!x     #               xxxx     xxxx                                 x!x  ",
   "                                      x!!xxxxxxxxxxx          xx           xx                                x!x  ",
   "                                      xx!!!!!!!!!!xx         xx             xx                q              x!x  ",
   "                                       xxxxxxxxxx!!x         x                                    o   o   o  x!x  ",
   "                                                xx!x              o   o                                 r  xx!x   ",
   "                                                 x!x                                         xxxxxxxxxxxxxxx!!x   ",
   "                                          -      xxx              q   q                        !!!!!!!!!!!!!!xx   ",
   "                             o    q                          >x  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                     o                                         xxxx!!!!!xxxx      #                               ",
   "                                              xx     xx           xxxxxxx  -     xxx         xxx                  ",
   "                     x                         x    xx                             x         x x                  ",
   "              q      x                         x     x                             x         x                    ",
   "                    xx                         x     xxx                       xxxxx         x                    ",
   "                 o xxx             #           xx    x                             x         x                    ",
   "                xxxxxx                         x     x      o o o    x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "            o xxxxxxxxx         x   x          x     x    xxxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xxxxxxxxxxx        x o x          x   xxx               x   x   x               x                    ",
   "     @       xxxxxxxxxxx        x   x          x     x               x   x   x               x                    ",
   "    xxx      xxxxxxxxxxx        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    xxx      xxxxxxxxxxx       xx o xx         x     x            q  x     o     x x         x                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!xx   o    xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                   ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!x    o                xx!!!!!!xx !                    xx     xx                      ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!xx   0   xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!xxx!!!!!!xxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "  x                                                                                                        x  ",
   "  x                                                                                             q          x  ",
   "  x                                                                                                        x  ",
   "  x                                                        ! !!!!                                          x  ",
   "  x                                                        vxxxxv                                          x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                 !!!!!!                                                                 x  ",
   "  x                                 vxxxxv                                                                 x  ",
   "  x                                                                                                x       x  ",
   "  x                                                                                                        x  ",
   "  x                                                        !!!        !!!          !!!!!!                  x  ",
   "  x                                                        !x!        !x!          vxxxxv                  x  ",
   "  x        xxx                           xxx               vx     #     x                                  x  ",
   "  x                                       x                 x   oooo   x       xxx                         x  ",
   "  x                                               q         =  =  =  = =                                   x  ",
   "  x                                                         xxxxxxxxxxxx                                   x  ",
   "  x                                              x           x                                             x  ",
   "  x                                       xx   xxxx   xx    xx              x x                            x  ",
   "  x                    @                  x           x                    x!!!x                           x  ",
   "  x                   xxxx             q                                    xxx                            x  ",
   "  x                                       xx          x                                                    x  ",
   "  x                                        = = = =    x            xxx                                     x  ",
   "  x                                                   x      =    = = =                         xx |x      x  ",
   "  x                                            = = = =x     o                xxx                           x  ",
   "  x                                  xx   xx          x              =          =        #                 x  ",
   "  x                           o   o   x   x           x    xx                xxv        xxx                x  ",
   "  x                                   x   x           x              x       = = =         =               x  ",
   "  x                           v!!    xxx xxx     o o  x!!!!!!!!!!!!!!x                                     x  ",
   "  x                            xxx x x xxx x      #   x!!!!!!!!!!!!!!x                                     x  ",
   "  x                                        x  |xxxxxxxxxxxxxxxxxxxxxxx               |          |   |      x  ",
   "  x                                       xx                                         xxx                   x  ",
   "  x                                       x                                         x!!!x                  x  ",
   "  x                                       x    =   =     =      =        =           vvv                   x  ",
   "  x                                       x                  q           xx                                x  ",
   "  x                                     x                                x   x                             x  ",
   "  x                                       x                              x                                 x  ",
   "  x                 o                       x     |xxxx|   |     |     x   x                               x  ",
   "  x                xxx                    x                                                                x  ",
   "  x                 x                      x                            xxx                                x  ",
   "  x                 x           #  x        x                           x x                                x  ",
   "  x                 x         xxxxxxxxxxxxx            x oo x    x oo  xx xx                             r x  ",
   "  x           q     x         x           x!!x  =    =  =   x!!!!x    xx   xx     =  =    =  x=     x      x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "    @                                                                                                         ",
   "    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                          ",
   "                                                                                                              ",
   "	x     x   xxxxxx   x      x       x                  x    xx     x       x    xx                            ",
   "	x     x   x    x   x      x        x                x     xx     x x     x    xx                            ",
   "	x     x   x    x   x      x         x      x       x      xx     x  x    x    xx                            ",
   "	 x    x   x    x   x      x          x    x  x    x       xx     x   x   x    xx                            ",
   "	  xxxx    x    x   x      x           x  x    x  x        xx     x    x  x    xx                            ",
   "		 x      x    x   x      x            x        x         xx     x     x x    xx                            ",
   "		 x      x    x   x      x            x        x         xx     x      xx                                  ",
   "		 x      xxxxxx   xxxxxxxx            x        x         xx     x       x    xx                            "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
